server:
  port: 8080
---
spring:
  config:
    import: "optional:file:./recommendation-service/app.env[.properties]"
  jpa:
    defer-datasource-initialization: true
  cloud:
    function:
      definition: genreUpdatedEventConsumer; movieAddedEventConsumer
    stream:
      bindings:
        genreUpdatedEventConsumer-in-0:
          destination: customer-events
          group: recommendation-service
        movieAddedEventConsumer-in-0:
          destination: movie-events
          group: recommendation-service
      kafka:
        binder:
          brokers:
            - localhost:8081
            - localhost:8082
            - localhost:8083
          # security config
          configuration:
            security.protocol: SASL_SSL
            ssl.truststore.type: JKS
            ssl.truststore.location: classpath:/kafka_config/kafka.truststore.jks
            ssl.truststore.password: ${KAFKA_TRUSTSTORE_PASSWORD}
            sasl.mechanism: PLAIN
            sasl.jaas.config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USER}" password="${KAFKA_PASSWORD}";'